### PR TITLE
ci: release automation

### PR DESCRIPTION
**Pull request by cletustboone**
- Adds [GitHub Actions automation](https://github.com/rdkcentral/firebolt-core-sdk/actions/workflows/release-github.yml) for manually triggering a release to GitHub.
- Use [commitlint](https://commitlint.js.org/#/) to enforce the [conventional-commit standard](https://www.conventionalcommits.org/en/v1.0.0/).
- Use [husky](https://typicode.github.io/husky/#/) to install client-side git hooks to enforce conventional-commit standard.
- Use `semantic-release` to generate release notes and auto-update `package.json` version.

### CODE REVIEW

**Comment by mhughesacn** [comment]
Hi Cletus,
There is a short code match here but I can't justify it as boilerplate or config, so it does need to be credited please:
- In NOTICE, append:
```
Material from husky is:
Copyright (c) 2021 typicode
Licensed under the MIT License
```
- In LICENSE, please append a copy of the MIT license from https://github.com/typicode/husky/blob/main/LICENSE but use the generic form:
```
MIT License

Copyright <YEAR> <COPYRIGHT HOLDER>

Permission is ...
```

Thank you,
Martin Hughes, RDK CMF Compliance Team

**Comment by jlacivita** [comment]
@mhughesacn : I can't seem to open the link provided. Which code has been flagged?

URL: https://protex.cmf.code.rdkcentral.com/p/projects/c_cmfrdkcentralfirebolt-core-sdk_7716

**Comment by mhughesacn** [comment]
Hi @jlacivita @cletustboone: The code match is in the gist.  It is the commit-msg file which comes from the husky repo.  As the credit is in place, I just upvoted.  Thank you!

**Comment by cletustboone** [comment]
I plan to remove the [is-ci dependency](https://github.com/rdkcentral/firebolt-core-sdk/commit/4575dc5101cff365bc68603f1a6d7e7b3a806fce#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R43) in an upcoming commit.

**Pull request merged**
