### PR TITLE
Augment ContentDiscoveryIntent with more context

### PR DESCRIPTION
**Pull request by cletustboone**
This adds the optional `filters` and `keywords` properties to the payload of the ContentDiscoveryIntent. The presence of these properties allow for context-aware systems to communicate their context back to an aggregated experience.

As an example, a catalog-aware discovery system on a given distribution platform may want to pass catalog-specific context downstream to an aggregated experience to meet a particular product requirement.

## Filters

~If the `filters` property is present, a catalog-aware system has determined that a user search results exist for a particular `programType` and/or `offeringType`. This context may be used to power behavior in an aggregated experience.~

`filters` are just hints that can be applied to a subsequent search from the aggregated experience. They are modeled as:
```typescript
type Filter = {
  key: String,
  value: String
}
```

## Keywords

Some content discovery systems require special treatment of content belonging to particular providers. The presence of the `keywords` property indicates that a catalog-aware system has determined that  a particular app on the platform has advertised itself as having results pertinent to the user's query. An aggregated experience may execute business logic given this knowledge. Keywords are modeled as:
```typescript
type Keyword = {
  keyword: String,
  type: String,
  appId: String
}
```

### CODE REVIEW

**Comment by cletustboone** [comment]
My linter had a lot of problems with the way things were formatted here. If you want to see the actual meat of this PR, please check commit https://github.com/rdkcentral/firebolt-core-sdk/pull/5/commits/b4cfa124d638a75877dc032b25483aa62939e83a specifically.

**Comment by cletustboone** [comment]
Also, examples still need to be updated. Just putting this here to make sure it's what we talked about.

**Comment by jlacivita** [comment]
LGTM, but needs main merged in first.

**Comment by cletustboone** [comment]
I need to take a run at generating the docs and making sure my changes show up, so won't merge until I verify things.

**Comment by cletustboone** [comment]
I took a crack at adding an example response for `ContentDiscoveryIntent`. Below is the generated markdown.

---
### ContentDiscoveryIntent

```typescript
type ContentDiscoveryIntent = {
  action: "discovery"
  context: {
    source: 'voice' | 'editorial' | 'device'
  }
  data: {
    query: string
    filters?: object[]
    keywords?: object[]
    menus?: string[]
    federation?: object[]
  }
}
```




<details>
  <summary><b>Examples</b></summary>

```json
{
  "action": "contentDiscovery",
  "context": {
    "source": "voice"
  },
  "data": {
    "query": "Bill Murray Comedies in 4K",
    "filters": [
      {
        "key": "videoResolution",
        "value": "UHD"
      }
    ],
    "keywords": [
      {
        "keyword": "Bill Murray",
        "type": "Person",
        "appId": "FooApp"
      },
      {
        "keyword": "Comedies",
        "type": "Genre",
        "appId": "FooApp"
      }
    ],
    "menus": [
      "abcdef",
      "ghijkl"
    ],
    "federation": [
      {
        "appId": "BarApp",
        "exclude": false
      }
    ]
  }
}
```

</details>

#### Details

A Firebolt compliant representation of a user intention to discover content with out a clear specific entity match.

---
I'd like to discuss the example a little bit. The query _Bill Murray Comedies in 4K_ hopefully shows the intention of each property.

### filters

So, first of all, the voice system was able to determine that the user wants only UHD content, hence:
```
    "filters": [
      {
        "key": "videoResolution",
        "value": "UHD"
      }
    ]
```
Since these key/value pairs aren't standardized, the voice system needs awareness of which content discovery backend the aggregated experience may eventually use to resolve this query in order to pass back filter key/value pairs that will be of any use.

### keywords

Next, the voice system realized, through some back-office integration, that `FooApp` has results relevant to the keywords detected by the NLP, so:
```
"keywords": [
      {
        "keyword": "Bill Murray",
        "type": "Person",
        "appId": "FooApp"
      },
      {
        "keyword": "Comedies",
        "type": "Genre",
        "appId": "FooApp"
      }
    ],
```
These may be used by the aggregated experience in order to show special results from `FooApp`.

### Menus

The voice system has identified editorial content that may be used by the aggregated experience:
```
"menus": [
      "abcdef",
      "ghijkl"
    ],
```
Again, the voice system needs to be aware of the AE's editorial back office in order for these values to be of use.

### federation

Finally, the voice system has determined that the user may have purchased content from `BarApp` that might be relevant to this query.
```
    "federation": [
      {
        "appId": "BarApp",
        "exclude": false
      }
    ]
```
I need some help on this one. Do I have this use case right?

**Review by jlacivita — DISMISSED** [review]
LGTM

**Comment by cletustboone** [comment]
I'm still not authorized to merge. `main` is a protected branch and I don't have sufficient privs to merge, so go ahead at your leisure.

**Review by jlacivita — APPROVED** [review]

**Pull request merged**
